# Generated by Django 4.1.2 on 2022-12-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_caption_post_link_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='Link',
            field=models.TextField(blank=True),
        ),
    ]
