# Generated by Django 4.1.2 on 2022-12-19 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Link',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Description',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_images'),
            preserve_default=False,
        ),
    ]
