# Generated by Django 4.1.2 on 2022-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_link_post_caption_remove_post_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Link',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
