# Generated by Django 4.1.2 on 2022-12-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_link_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Link',
            field=models.TextField(default='No Link'),
        ),
    ]
