# Generated by Django 4.1.2 on 2022-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Link',
            field=models.URLField(default='No Link'),
        ),
    ]
