version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
      image: mysql:latest  # use the latest postgres image
      volumes:
        - ./data/mysql/db:/var/lib/mysql
      environment:
        MYSQL_DATABASE: 'django'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_HOST: db
        MYSQL_PORT: 3306  # cannot change this port to other number
        MYSQL_USER : root
      ports:
        - "3306:3306"  # map port 8000 on host to port 8000 in container
      container_name: mysql_db
