
version: "3.8"
services:
  app:
    build: .  # build from Dockerfile in current directory
    volumes:
      - .:/app  #
    ports:
      - "8000:8000"  # map port 8000 on host to port 8000 in container
    image: app:latest  # tag the image as app:latest
    container_name: mylocalcontainer  # name the container as swe573_term_project
    command: >
      sh 
      -c "sleep 10 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py makemigrations core &&
             python manage.py migrate core &&
             python manage.py runserver 0.0.0.0:8000"
    stdin_open: true 
    tty: true
    depends_on:
      - db
  db:
    image: mysql:latest  # use the latest postgres image
    volumes:
      - mysql_db_test_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'django'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306  # cannot change this port to other number
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_USER : root
    ports:
      - "3307:3306"  # map port 8000 on host to port 8000 in container
    container_name: mysql_db

volumes:
    mysql_db_test_vol: